name: learn_dart
description: A Dart package to learn the Dart programming language.
version: 1.0.0
repository: https://github.com/EmrecanKaracayir/learn_dart

environment:
  sdk: ^3.7.2

# dependencies:
# path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
